# Use a Node.js base image
FROM node:16

# Set the working directory inside the container
WORKDIR /frontend

# Copy package.json and package-lock.json for npm install
COPY package*.json /frontend/

# Install the Node.js dependencies
RUN npm install

# Copy the entire frontend application
COPY . /frontend/

# Expose the port your frontend app runs on
EXPOSE 3000

# Run the frontend app
CMD ["npm", "start"]
